### ISSUE TITLE
Argument Align

### ISSUE THREAD

**Issue by 5ebastianMeier** [5minds/typescript-guidelines#13]
Habe aktuell ein Problem mit folgender Regel: https://palantir.github.io/tslint/rules/align/

Wenn ich versuche so einen Timeout zu setzen:
```
    setTimeout(() => {
      const entry = cacheRepository.get(testHash);
      if (!entry) {
        next();
      }
    }, interval * 2);
```

Korrigiert TSLint das zu diesem Ergebnis:
```
    setTimeout(() => {
      const entry = cacheRepository.get(testHash);
      if (!entry) {
        next();
      }
    },         interval * 2);
```

mit der Begründung: `[tslint] arguments are not aligned (align)`

Halte das für unglücklich - wie seht ihr das?

**Comment by moellenbeck** [comment]
Dito! Hätte ich nicht erwartet.

**Comment by LeoTT** [comment]
Hab gerade getestet und es gibt noch eine Möglichkeit obigen Ausdruck darzustellen ohne Warnung.
```typescript
setTimeout(
  () => {
    const entry = cacheRepository.get(testHash);
    if (!entry) {
      next();
    }
  },         
  interval * 2);
```
Hilft vielleicht sogar dem unerfahrenen JavaScriptler die Arrow-Function als eigenes Argument zu erkennen.

Das mit den Leerzeichen lasse ich mir auch nicht aufzwingen, bisher bei diesen Zeilen die Regel mit Kommentar deaktiviert. Bin aber auch kein Fan von linter-Anweisungen in meinem Programm.

**Comment by 5ebastianMeier** [comment]
Habe gerade mit @LeoTT gesprochen und uns ist aufgefallen, dass es genügen sollte Argumente aus der Regel auszuschließen - wir profitieren bei Methodenaufrufen vermutlich niemals besonders von der Regel - bei Parametern hingegen halte ich sie für sinnvoll
