### ISSUE TITLE
current "whitespace"-rule enforces spaces in imports

### ISSUE THREAD

**Issue by heikomat** [5minds/typescript-guidelines#5]
The current whitespace-rule has the property "[check-module](https://github.com/5minds/typescript-guidelines/blob/f43f470558593cdb3e2075bae47e358677f2cccc/tslint-config-5minds/tslint.json#L150)", which enforces whitespaces in named imports.

As far as i know, we want imports like this:
```TypeScript
import {FrameworkConfiguration} from 'aurelia-framework';
```
but the current whitespace-setting enforces this:
```TypeScript
import { FrameworkConfiguration } from 'aurelia-framework';
```

This is probably because of [this bug](https://github.com/palantir/tslint/issues/2401) that was [fixed in tslint 5.5.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v550)

**Comment by LeoTT** [comment]
Good catch, fixed with following feature branch #7
